### ISSUE TITLE
"pier_line" doesn't match ClearTable's "pier_line_raw"

### ISSUE THREAD

**Issue by nyurik** [kartotherian/meddo#3]
ClearTables generate pier_line_raw table, not pier_line that's expected by meddo

**Comment by pnorman** [comment]
ClearTables generates both, see https://github.com/ClearTables/ClearTables/blob/master/sql/post/pier_line.sql

**Comment by nyurik** [comment]
Turns out I forgot the post-import steps as described in https://github.com/ClearTables/ClearTables#usage
